export const PROJECTS_KEY = "PROJECTS";
export const COLUMNS_KEY = "COLUMNS";
export const TASKS_KEY = "TASKS";

// AppWrite Constants
export const {
  VITE_APPWRITE_ENDPOINT: ENDPOINT,
  VITE_APPWRITE_PROJECT_ID: PROJECT_ID,
  VITE_APPWRITE_DATABASE_ID: DATABASE_ID,
  VITE_APPWRITE_PROJECTS_COLLECTION_ID: PROJECTS_COLLECTION_ID,
  VITE_APPWRITE_COLUMNS_COLLECTION_ID: COLUMNS_COLLECTION_ID,
  VITE_APPWRITE_TASKS_COLLECTION_ID: TASKS_COLLECTION_ID,
} = import.meta.env;
